--From: (Server)
--To: (Server)
/*
INSERT INTO IBK_RENTABILIDAD_ACUM
SELECT * 
FROM IBK_RENTABILIDAD
WHERE 1=1
AND CODMES = (SELECT MIN(CODMES) FROM IBK_RENTABILIDAD)
*/

INSERT INTO IBK_RENTABILIDAD_ACUM
SELECT 
J.CODMES,
J.CODUNICOCLI,
ISNULL(J.MTO_INTERES,0)+ISNULL(Z.MTO_INTERES,0),
ISNULL(J.MTO_COMIS,0)+ISNULL(Z.MTO_COMIS,0),
ISNULL(J.MTO_INOF,0)+ISNULL(Z.MTO_INOF,0),
ISNULL(J.MTO_RECUP_CASTIG,0)+ISNULL(Z.MTO_RECUP_CASTIG,0),
ISNULL(J.MTO_GASTO_MONO_ALINEA,0)+ISNULL(Z.MTO_GASTO_MONO_ALINEA,0),
ISNULL(J.MTO_COST_FOND,0)+ISNULL(Z.MTO_COST_FOND,0),
ISNULL(J.MTO_INTERES_GEN,0)+ISNULL(Z.MTO_INTERES_GEN,0),
ISNULL(J.MTO_COMIS_GEN,0)+ISNULL(Z.MTO_COMIS_GEN,0),
ISNULL(J.MTO_INOF_GEN,0)+ISNULL(Z.MTO_INOF_GEN,0),
ISNULL(J.MTO_COST_FOND_GEN,0)+ISNULL(Z.MTO_COST_FOND_GEN,0),
ISNULL(J.MTO_RESERVA,0)+ISNULL(Z.MTO_RESERVA,0),
ISNULL(J.MTO_RESERVA_ADIC,0)+ISNULL(Z.MTO_RESERVA_ADIC,0),
ISNULL(J.MTO_SALDO_PROM_MES,0)+ISNULL(Z.MTO_SALDO_PROM_MES,0),
ISNULL(J.MTO_GASTO_OPER_DIR,0)+ISNULL(Z.MTO_GASTO_OPER_DIR,0),
ISNULL(J.MTO_GASTO_OPER_INDIR,0)+ISNULL(Z.MTO_GASTO_OPER_INDIR,0),
ISNULL(J.MTO_GASTO_OPER_CANAL,0)+ISNULL(Z.MTO_GASTO_OPER_CANAL,0),
ISNULL(J.RENTABILIDAD,0)+ISNULL(Z.RENTABILIDAD,0)
FROM IBK_RENTABILIDAD J
LEFT JOIN IBK_RENTABILIDAD_ACUM Z ON DBO.MES(J.CODMES,-1)=Z.CODMES AND J.CODUNICOCLI=Z.CODUNICOCLI
WHERE 1=1
AND J.CODMES = (SELECT MAX(DBO.MES(CODMES,1)) FROM IBK_RENTABILIDAD_ACUM)
