--FROM: DWHGYSBP
--TO: IBK_RENTABILIDAD
SELECT 
CODMES, CIF_KEY CODUNICOCLI,
MTO_INTERES,
MTO_COMIS,
MTO_INOF,
MTO_RECUP_CASTIG,
MTO_GASTO_MONO_ALINEA,
MTO_COST_FOND,
MTO_INTERES_GEN,
MTO_COMIS_GEN,
MTO_INOF_GEN,
MTO_COST_FOND_GEN,
MTO_RESERVA,
MTO_RESERVA_ADIC,
MTO_SALDO_PROM_MES,
MTO_GASTO_OPER_DIR,
MTO_GASTO_OPER_INDIR,
MTO_GASTO_OPER_CANAL,
NVL(MTO_INTERES,0) + NVL(MTO_COMIS,0) + NVL(MTO_INOF,0) + NVL(MTO_RECUP_CASTIG,0) + NVL(MTO_INTERES_GEN,0) + NVL(MTO_COMIS_GEN,0) + NVL(MTO_INOF_GEN,0)
- (NVL(MTO_GASTO_MONO_ALINEA,0) + NVL(MTO_COST_FOND,0) + NVL(MTO_COST_FOND_GEN,0) + NVL(MTO_RESERVA,0) + NVL(MTO_RESERVA_ADIC,0) + NVL(MTO_GASTO_OPER_DIR,0) +  NVL(MTO_GASTO_OPER_INDIR,0) + NVL(MTO_GASTO_OPER_CANAL,0)) RENTABILIDAD
FROM DWHGYS_VIS.T_GYS_RENT_HIP
