/*
Trazabilidad diaria de refinanciados
*/

INSERT INTO STG.PRE_TRAZABILIDAD_REFINANCIADOS_DIARIO
SELECT 
J.CODMES,
J.CODUNICOCLI,
J.NROPROD,
Z.NROPROD NPOLDC14
FROM 
(
	--CUENTAS DE LOS CLIENTES REFINANCIADOS
	SELECT *  
	FROM STG.IBK_CIERRE_DIARIO J
	WHERE 1=1
	AND J.PROD = '08 Refinanciados'
	AND J.CODMES	=	(SELECT CODMES	FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
	AND J.DIA		=	(SELECT DIA		FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
	AND J.CODUNICOCLI IN (
		SELECT J.CODUNICOCLI 
		FROM STG.IBK_CIERRE_DIARIO J
		LEFT JOIN DBO.MAE_HIPOTECARIO Z ON J.CODUNICOCLI=Z.CODUNICOCLI AND J.NROPROD=Z.NROPROD
		WHERE 1=1
		AND J.PROD = '08 Refinanciados'
		AND Z.CODUNICOCLI IS NULL
		AND J.CODMES	=	(SELECT CODMES	FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
		AND J.DIA		=	(SELECT DIA		FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
	) 
) J
LEFT JOIN 
(
	--CUENTAS DE LOS CLIENTES ANTES DE REFINANCIAR
	SELECT *  
	FROM STG.IBK_CIERRE_DIARIO J
	WHERE 1=1
	AND J.PROD != '08 Refinanciados'
	AND J.CODMES	=	(SELECT CODMES	FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID)   FROM NFO.IBK_FECHAS))
	AND J.DIA		=	(SELECT DIA		FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID)-1 FROM NFO.IBK_FECHAS))
	AND J.CODUNICOCLI IN (
		SELECT J.CODUNICOCLI 
		FROM STG.IBK_CIERRE_DIARIO J
		LEFT JOIN DBO.MAE_HIPOTECARIO Z ON J.CODUNICOCLI=Z.CODUNICOCLI AND J.NROPROD=Z.NROPROD
		WHERE 1=1
		AND J.PROD = '08 Refinanciados'
		AND Z.CODUNICOCLI IS NULL
		AND J.CODMES	=	(SELECT CODMES	FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
		AND J.DIA		=	(SELECT DIA		FROM NFO.IBK_FECHAS WHERE ID = (SELECT MAX(ID) FROM NFO.IBK_FECHAS))
	)
) Z ON J.CODUNICOCLI=Z.CODUNICOCLI
WHERE J.NROPROD<>Z.NROPROD
